# General settings
experiment_name: "graph_based_model_experiment"
random_seed: 42
device: "cuda"  # or "cpu"

# Data settings
data:
  train_data_path: "sample_datasets/train_data.csv"
  val_data_path: "sample_datasets/val_data.csv"
  test_data_path: "sample_datasets/test_data.csv"
  batch_size: 32
  num_workers: 4

# Model settings
model:
  input_dim: 10
  hidden_dim: 64
  output_dim: 1
  use_attention: True

# Training settings
training:
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 1e-5
  patience: 10
  step_size: 10
  gamma: 0.1

# Paths for saving results
output:
  checkpoints_dir: "outputs/checkpoints/"
  logs_dir: "outputs/logs/"
  results_dir: "outputs/results/"
